google:
  location:
    uri: https://maps.googleapis.com/maps/api/place/queryautocomplete/json?key=
    key: AIzaSyA_NS9JFYgkEm3HOHeDtDok_g3PVI-2MY4
    querystring: input=
    lang.attribute: language=
    lang.pref: es
logging:
    level:
      org.springframework.web: ERROR
      com.project.locate: INFO
    path: project/logs